name: glass_fish_button
description: >-
  A glassmorphism-inspired Flutter button widget with switchable light and dark themes.
version: 0.1.1
#publish_to: 'pub.dev'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
